development:
  server: "http://localhost:9292/faye/faye"
  secret_token: "secret"
test:
  server: "http://localhost:9292/faye/faye"
  secret_token: "secret"
production:
  server: "https://gentle-forest-8025.herokuapp.com/faye"
  secret_token: "bnelson-chat"
  signature_expiration: 86400 # one day
